[package]
name = "shadowenv"
version = "1.0.0"
authors = ["Burke Libbey <burke@libbey.me>", "Lisa Ugray <lisa.ugray@shopify.com>", "Aaron Olson <aaron.olson@shopify.com>"]
edition = "2018"


[dependencies]
blake2 = "0.8.0"
ketos = "0.10"
ketos_derive = "0.10"
serde_json = "1.0.37"
serde = "1.0.85"
serde_derive = "1.0.85"
failure = "0.1.5"
clap = "2.32.0"
signatory = "0.10.1"
signatory-dalek = "0.10.0"
hex = "0.3.2"
regex = "1.1.0"
dirs = "1.0.4"
libc = "0.2.48"
